### ISSUE TITLE
Plugin Deletion Issue

### ISSUE THREAD

**Issue by jtiki** [jrief/djangocms-cascade#180]
I recently upgrade and am now hitting the following issue:

```
Internal Server Error: /en/admin/cms/page/delete-plugin/1350/
Traceback (most recent call last):
  File "/srv/jeremyspencer.me/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/srv/jeremyspencer.me/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/srv/jeremyspencer.me/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/srv/jeremyspencer.me/venv/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/srv/jeremyspencer.me/venv/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 244, in inner
    return view(request, *args, **kwargs)
  File "/srv/jeremyspencer.me/venv/lib/python2.7/site-packages/django/views/decorators/clickjacking.py", line 39, in wrapped_view
    resp = view_func(*args, **kwargs)
  File "/srv/jeremyspencer.me/venv/lib/python2.7/site-packages/cms/admin/placeholderadmin.py", line 629, in delete_plugin
    [plugin], opts, request.user, self.admin_site, using)
  File "/srv/jeremyspencer.me/venv/lib/python2.7/site-packages/django/contrib/admin/utils.py", line 128, in get_deleted_objects
    collector.collect(objs)
  File "/srv/jeremyspencer.me/venv/lib/python2.7/site-packages/django/contrib/admin/utils.py", line 193, in collect
    return super(NestedObjects, self).collect(objs, source_attr=source_attr, **kwargs)
  File "/srv/jeremyspencer.me/venv/lib/python2.7/site-packages/django/db/models/deletion.py", line 230, in collect
    elif sub_objs:
  File "/srv/jeremyspencer.me/venv/lib/python2.7/site-packages/django/db/models/query.py", line 266, in __nonzero__
    return type(self).__bool__(self)
  File "/srv/jeremyspencer.me/venv/lib/python2.7/site-packages/django/db/models/query.py", line 262, in __bool__
    self._fetch_all()
  File "/srv/jeremyspencer.me/venv/lib/python2.7/site-packages/django/db/models/query.py", line 1074, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/srv/jeremyspencer.me/venv/lib/python2.7/site-packages/django/db/models/query.py", line 52, in __iter__
    results = compiler.execute_sql()
  File "/srv/jeremyspencer.me/venv/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 848, in execute_sql
    cursor.execute(sql, params)
  File "/srv/jeremyspencer.me/venv/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/srv/jeremyspencer.me/venv/lib/python2.7/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/srv/jeremyspencer.me/venv/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
ProgrammingError: relation "cmsplugin_cascade_sharableelement" does not exist
LINE 1: ...ascade_sharableelement"."shared_glossary_id" FROM "cmsplugin...
```
I made sure all of the migrations were applied correctly but the issue is still persisting. Any suggestions on where to start looking?

**Comment by jtiki** [comment]
Never mind, after reinstalling all of my dependencies the issue subsided. There must have been a version mismatch somewhere.
