### ISSUE TITLE
Model import leads to cyclic import

### ISSUE THREAD

**Issue by lgandras** [jrief/djangocms-cascade#260]
Hi Jacob!

We recently intend to migrate to Django-1.11, which involves updating lots of packages. The following started occuring when trying to execute a migration:

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "venv/lib/python3.5/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "venv/lib/python3.5/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "venv/lib/python3.5/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "venv/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "venv/lib/python3.5/site-packages/cmsplugin_cascade/models.py", line 208, in <module>
    class IconFont(models.Model):
  File "venv/lib/python3.5/site-packages/cmsplugin_cascade/models.py", line 220, in IconFont
    font_folder = FilePathField(allow_files=False, allow_folders=True)
  File "venv/lib/python3.5/site-packages/cmsplugin_cascade/models.py", line 198, in __init__
    kwargs.setdefault('path', app_settings.CMSPLUGIN_CASCADE['icon_font_root'])
  File "venv/lib/python3.5/site-packages/cmsplugin_cascade/app_settings.py", line 141, in CMSPLUGIN_CASCADE
    settings_module = import_module('{}.settings'.format(module_name))
  File "venv/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 944, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "widgets/widget_html_code/cascade.py", line 10, in <module>
    from xx_core.cascade.plugin_base import XXXXXXXXXPluginMixin, PluginCommonBase
  File "xx_core/cascade/plugin_base.py", line 17, in <module>
    from cmsplugin_cascade.plugin_base import CascadePluginBase, CascadePluginBaseMetaclass
  File "venv/lib/python3.5/site-packages/cmsplugin_cascade/plugin_base.py", line 27, in <module>
    from .hide_plugins import HidePluginMixin
  File "venv/lib/python3.5/site-packages/cmsplugin_cascade/hide_plugins.py", line 12, in <module>
    class HidePluginMixin(object):
  File "venv/lib/python3.5/site-packages/cmsplugin_cascade/hide_plugins.py", line 17, in HidePluginMixin
    suppress_template = engines['django'].from_string('')
  File "venv/lib/python3.5/site-packages/django/template/utils.py", line 80, in __getitem__
    engine = engine_cls(params)
  File "venv/lib/python3.5/site-packages/django/template/backends/django.py", line 30, in __init__
    options['libraries'] = self.get_templatetag_libraries(libraries)
  File "venv/lib/python3.5/site-packages/django/template/backends/django.py", line 48, in get_templatetag_libraries
    libraries = get_installed_libraries()
  File "venv/lib/python3.5/site-packages/django/template/backends/django.py", line 113, in get_installed_libraries
    for name in get_package_libraries(pkg):
  File "venv/lib/python3.5/site-packages/django/template/backends/django.py", line 126, in get_package_libraries
    module = import_module(entry[1])
  File "venv/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "venv/lib/python3.5/site-packages/filer/templatetags/filer_admin_tags.py", line 7, in <module>
    from ..admin.tools import admin_url_params, admin_url_params_encoded
  File "venv/lib/python3.5/site-packages/filer/admin/__init__.py", line 10, in <module>
    from .folderadmin import FolderAdmin
  File "venv/lib/python3.5/site-packages/filer/admin/folderadmin.py", line 62, in <module>
    Image = load_model(FILER_IMAGE_MODEL)
  File "venv/lib/python3.5/site-packages/filer/utils/loader.py", line 48, in load_model
    return apps.get_model(*model_name_tuple)
  File "venv/lib/python3.5/site-packages/django/apps/registry.py", line 193, in get_model
    self.check_models_ready()
  File "venv/lib/python3.5/site-packages/django/apps/registry.py", line 132, in check_models_ready
    raise AppRegistryNotReady("Models aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.
```
If you take a close look, the import leads to *cmsplugin_cascade* models. This, because of a default parameter value for  `kwargs.setdefault('path', app_settings.CMSPLUGIN_CASCADE['icon_font_root'])` leads to the import of settings. Settings lead finally to the import of all plugins, which may in turn, depend on further models, which leads to recursion.

I know that default for the path kwarg is already like that since a long time, but it doesn't necessarily mean it's right. Given this is happening on *import* time, shouldn't models avoid importing all plugins?

cheers,
Andras

**Comment by jrief** [comment]
Hi Andras,
which version of Cascade?

**Comment by lgandras** [comment]
djangocms-cascade==0.15.2

cheers,
Andras

**Comment by jrief** [comment]
lets move the discussion to Gitter. The URL is on the front page.

**Comment by haricot** [comment]
@lgandras, it may be related to this issue #262

**Comment by lgandras** [comment]
Hi,

the problem was that previously, widget were specified in the settings in this way:
`CMSPLUGIN_CASCADE_PLUGINS = ['widget.cascade']`
Since *0.13* (http://djangocms-cascade.readthedocs.io/en/latest/changelog.html), they must be referenced this way:
`CMSPLUGIN_CASCADE_PLUGINS = ['widget']`
Additionally, adding a `settings.py` inside the module with `CASCADE_PLUGINS = ['cascade']`makes sure the plugins are loaded at the proper time.

Ignoring the previous release notes referenced my plugins on settings load time, which is wrong. Making sure you reference only the module settings inside the main settings is the proper way to upgrade.

**Comment by jrief** [comment]
@lgandras since it's solved, can we close it?

**Comment by jproffitt** [comment]
@lgandras @jrief I am also having this issue.

We were previously using django 1.10 with djangocms-cascade 0.12.3. We upgrading to django 1.11 and djangocms-cascade 0.15.4, which is when the issue happened.

We define this setting:

```
CMSPLUGIN_CASCADE_PLUGINS = (
    'cmsplugin_cascade.bootstrap3.container',
)
```
since we only want the container plugins. The docs say that is allowed: http://djangocms-cascade.readthedocs.io/en/latest/installation.html#activate-the-plugins.

However, that causes the `AppRegistryNotReady` error as mentioned above. Can we no longer use only the container plugins? If we can, what is the proper way to do that now? The release notes linked above to not mention anything about having to change settings, and you can see the installation docs still say you can do `'cmsplugin_cascade.bootstrap3.container'`.

**Comment by jrief** [comment]
OK, I will try to reproduce your setup and look for a solution.
