### ISSUE TITLE
Plugin carousel as specified in cmsplugin_cascade.bootstrap3.settings.CMSPLUGIN_CASCADE_PLUGINS could not be loaded

### ISSUE THREAD

**Issue by ngn1123** [jrief/djangocms-cascade#52]
Thank you for this terrific api.

I'm having trouble activating some of the plugins, particularly the carousel, image, and picture. In my settings.py, if I activate all plugins with:

CMSPLUGIN_CASCADE_PLUGINS = ('cmsplugin_cascade.bootstrap3',)

it throws the error in the title of this post. When I specify specific plugins such as buttons, collapsable, and container, it works, but it doesn't work for carousel, picture, and images.

**Comment by electroniceagle** [comment]
The setting names have changed.

# CMS Cascade
CMS_PLACEHOLDER_CONF = {
    'Page Content': {
        'plugins': ['BootstrapContainerPlugin'],
    },
}

CMS_CASCADE_PLUGINS = ('cmsplugin_cascade.bootstrap3', )

CMS_CASCADE_LEAF_PLUGINS = (
    'TextPlugin',
    'PicturePlugin',
    'LinkPlugin',
    'StylePlugin',
    'FormBuilderPlugin',
    'FilePlugin',
    'VideoPlugin',
    'VimeoVideoPlugin',
    'TabHeaderPlugin',
    'AccordionHeaderPlugin',
    'RepositoryDashboardPlugin',
    'SessionDashboardPlugin',
    'CMSLatestNewsPlugin',
)

**Comment by jrief** [comment]
In case of trouble, please always refer to the reference implementation. I always use it to test against, in case one of my customers runs into a problem.

**Comment by MelvinDRM** [comment]
I'm new in this matter of Django and Django CMS and I have the same error, what do you mean with "refer to the reference implementation", or what could be the cause of this?

Thanks in advance

**Comment by jrief** [comment]
With "refer to the reference implementation" I mean to start with the example project.
Everything you need for it, should be here:
http://djangocms-cascade.readthedocs.org/en/latest/impatient.html

**Comment by MelvinDRM** [comment]
Ah, I see the problem (I think).. 

I changed in bootstrap3.settings I changed CASCADE_PLUGIN for CMSPLUGIN_CASCADE_PLUGIN (which is what the error says) and then when I tried to run it, it gave the error django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.

According to what I've found, AppRegistryNotReady is something introduced in django 1.7, therefore the problem is that this is not made for Django 1.7.x, which is what I'm using for my project.

Anytime soon releasing a version 1.7 compatible?

**Comment by jrief** [comment]
Hmm, I was able to run it with django-1.7.
Wait, I'll retry.

**Comment by jrief** [comment]
I just tried with 1.7.3 and it works just as with 1.6.8.
There is a minor issue with django-select2 and django-1.7, therefore don't mix those, but for everything else it works fine.
Make sure to use django-cms 3.0.9

**Comment by MelvinDRM** [comment]
I'll check it out, thank you!

**Comment by MelvinDRM** [comment]
I made a clean install and using the link you gave me it works.

If I make a install using Django 1.7.3 and not using django_select2 it gives me the following warning:

----------------------------------------------------------------------------------------------------------------------------
System check identified some issues:

WARNINGS:
?: (1_6.W001) Some project unittests may not execute as expected.
	HINT: Django 1.6 introduced a new default test runner. It looks like this project was generated using Django 1.5 or earlier. You should ensure your tests are all running & behaving as expected. See https://docs.djangoproject.com/en/dev/releases/1.6/#new-test-runner for more information.
----------------------------------------------------------------------------------------------------------------------------

If I install it like I want it, it gives me the same "django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet" error.

I place my requirements and my settings.py just in case:

----------------------------------------------------------------------------------------------------------------------------
REQUIREMENTS.TXT
Django==1.7.3
Pillow>=2.7.0
South>=1.0.2
Unidecode>=0.04.16
argparse>=1.2.1
django-filer>=0.9.8
django-mptt>=0.6.1
django-polymorphic>=0.6
djangocms-admin-style>=0.2.5
easy-thumbnails
html5lib>=0.999
jsonfield>=1.0.0
six>=1.9.0
cmsplugin-filer==0.10.1
django-reversion>=1.8.5
dj-database-url==0.3.0
django-classy-tags==0.5.2
django-cms==3.0.9
django-sekizai==0.8.1
djangocms-cascade==0.4.1
djangocms-column==1.5
djangocms-file==0.1
djangocms-flash==0.1
djangocms-googlemap==0.2
djangocms-inherit==0.1
djangocms-installer==0.7.0
djangocms-link==1.5
djangocms-picture==0.1
djangocms-style==1.5
djangocms-teaser==0.1
djangocms-text-ckeditor==2.4.3
djangocms-video==0.1
pytz==2014.10
requests==2.5.1
----------------------------------------------------------------------------------------------------------------------------
SETTINGS.PY
import os
gettext = lambda s: s
DATA_DIR = os.path.dirname(os.path.dirname(__file__))
"""
Django settings for cmsApp project.

For more information on this file, see
https://docs.djangoproject.com/en/1.7/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.7/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
BASE_DIR = os.path.dirname(os.path.dirname(__file__))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.7/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '6o*0bl7nmzc3@+#2cedc!yu=b_-=gm6z7-=lbu6@b@1j!e#_o)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

TEMPLATE_DEBUG = True

ALLOWED_HOSTS = []


# Application definition





ROOT_URLCONF = 'cmsApp.urls'

WSGI_APPLICATION = 'cmsApp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.7/ref/settings/#databases



# Internationalization
# https://docs.djangoproject.com/en/1.7/topics/i18n/

LANGUAGE_CODE = 'en'

TIME_ZONE = 'America/Caracas'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.7/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(DATA_DIR, 'media')
STATIC_ROOT = os.path.join(DATA_DIR, 'static')

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'cmsApp', 'static'),
)
SITE_ID = 1

TEMPLATE_LOADERS = (
    'django.template.loaders.filesystem.Loader',
    'django.template.loaders.app_directories.Loader',
    'django.template.loaders.eggs.Loader'
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.doc.XViewMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'cms.middleware.user.CurrentUserMiddleware',
    'cms.middleware.page.CurrentPageMiddleware',
    'cms.middleware.toolbar.ToolbarMiddleware',
    'cms.middleware.language.LanguageCookieMiddleware'
)

TEMPLATE_CONTEXT_PROCESSORS = (
    'django.contrib.auth.context_processors.auth',
    'django.contrib.messages.context_processors.messages',
    'django.core.context_processors.i18n',
    'django.core.context_processors.debug',
    'django.core.context_processors.request',
    'django.core.context_processors.media',
    'django.core.context_processors.csrf',
    'django.core.context_processors.tz',
    'sekizai.context_processors.sekizai',
    'django.core.context_processors.static',
    'cms.context_processors.cms_settings'
)

TEMPLATE_DIRS = (
    os.path.join(BASE_DIR, 'cmsApp', 'templates'),
)

INSTALLED_APPS = (
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'djangocms_admin_style',
    'django.contrib.messages',
    'django.contrib.admin',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'djangocms_text_ckeditor',
    'cmsplugin_cascade',
    'cmsplugin_cascade.extra_fields',  # optional
    'cmsplugin_cascade.sharable',  # optional
    'cms',
    'menus',
    'mptt',
    'filer',
    'easy_thumbnails',
    'sekizai',
    'djangocms_style',
    'djangocms_column',
    'djangocms_file',
    'djangocms_flash',
    'djangocms_googlemap',
    'djangocms_inherit',
    'djangocms_link',
    'djangocms_picture',
    'djangocms_teaser',
    'djangocms_video',
    'reversion',
    'cmsApp'
)

LANGUAGES = (
    ## Customize this
    ('en', gettext('en')),
    ('es', gettext('es')),
    ('fr', gettext('fr')),
)

CMS_LANGUAGES = {
    ## Customize this
    'default': {
        'public': True,
        'hide_untranslated': False,
        'redirect_on_fallback': True,
    },
    1: [
        {
            'public': True,
            'code': 'en',
            'hide_untranslated': False,
            'name': gettext('en'),
            'redirect_on_fallback': True,
        },
        {
            'public': True,
            'code': 'es',
            'hide_untranslated': False,
            'name': gettext('es'),
            'redirect_on_fallback': True,
        },
        {
            'public': True,
            'code': 'fr',
            'hide_untranslated': False,
            'name': gettext('fr'),
            'redirect_on_fallback': True,
        },
    ],
}

CMS_TEMPLATES = (
    ## Customize this
    ('fullwidth.html', 'Fullwidth'),
    ('sidebar_left.html', 'Sidebar Left'),
    ('sidebar_right.html', 'Sidebar Right')
)

CMSPLUGIN_CASCADE_PLUGINS = ('cmsplugin_cascade.link','cmsplugin_cascade.bootstrap3',)

CMS_CASCADE_LEAF_PLUGINS = (
    'TextPlugin',
    'PicturePlugin',
    'LinkPlugin',
    'StylePlugin',
    'FormBuilderPlugin',
    'FilePlugin',
    'VideoPlugin',
    'TabHeaderPlugin',
    'AccordionHeaderPlugin',
    'RepositoryDashboardPlugin',
    'SessionDashboardPlugin',
    'CMSLatestNewsPlugin',
)

CMS_PERMISSION = True

CMS_PLACEHOLDER_CONF = {}

DATABASES = {
    'default':
        {'ENGINE': 'django.db.backends.sqlite3', 'NAME': 'project.db', 'HOST': 'localhost', 'USER': '', 'PASSWORD': '', 'PORT': ''}
}

MIGRATION_MODULES = {
    'cms': 'cms.migrations_django',
    'menus': 'menus.migrations_django',
    'djangocms_text_ckeditor': 'djangocms_text_ckeditor.migrations_django',
    'djangocms_column': 'djangocms_column.migrations_django',
    'djangocms_flash': 'djangocms_flash.migrations_django',
    'djangocms_googlemap': 'djangocms_googlemap.migrations_django',
    'djangocms_inherit': 'djangocms_inherit.migrations_django',
    'djangocms_style': 'djangocms_style.migrations_django',
    'djangocms_file': 'djangocms_file.migrations_django',
    'djangocms_link': 'djangocms_link.migrations_django',
    'djangocms_picture': 'djangocms_picture.migrations_django',
    'djangocms_teaser': 'djangocms_teaser.migrations_django',
    'djangocms_video': 'djangocms_video.migrations_django',
    'cmsplugin_cascade': 'cmsplugin_cascade.migrations',
}

THUMBNAIL_PROCESSORS = (
    'easy_thumbnails.processors.colorspace',
    'easy_thumbnails.processors.autocrop',
    'filer.thumbnail_processors.scale_and_crop_with_subject_location',
    #'easy_thumbnails.processors.scale_and_crop',
    'easy_thumbnails.processors.filters',
)

THUMBNAIL_HIGH_RESOLUTION = False

THUMBNAIL_PRESERVE_EXTENSIONS = True

THUMBNAIL_OPTIMIZE_COMMAND = {
    'png': '/opt/local/bin/optipng {filename}',
    'gif': '/opt/local/bin/optipng {filename}',
    'jpeg': '/opt/local/bin/jpegoptim {filename}',
}

#THUMBNAIL_DEBUG = True
----------------------------------------------------------------------------------------------------------------------------

**Comment by jeroenvlek** [comment]
I'm having the same AppRegistryNotReady issue with Django 1.7.1:

(datamantics_com)[jvlek@orochimaru datamantics.com]$ cat requirements.txt 
Django==1.7.1
Pillow==2.7.0
Unidecode==0.04.17
bcrypt==1.1.0
cffi==0.8.6
cmsplugin-filer==0.10.1
dj-database-url==0.3.0
dj-static==0.0.6
django-appconf==0.6
django-classy-tags==0.5.2
django-cms==3.0.9
django-filer==0.9.9
-e git://github.com/jeroenvlek/django-form-designer.git@71adc056e028efcb6e0a1303f798ea86ba9a715b#egg=django_form_designer-master
django-mptt==0.6.1
django-picklefield==0.3.1
django-polymorphic==0.6.1
django-reversion==1.8.5
django-sekizai==0.8.1
django-sslify==0.2.5
django-toolbelt==0.0.1
djangocms-admin-style==0.2.5
djangocms-cascade==0.4.1
djangocms-link==1.5
djangocms-picture==0.1
-e git://github.com/jeroenvlek/djangocms-revealjs.git@a81084228404a2b1f6ab0532fcbce5b74a6c2348#egg=djangocms_revealjs-master
djangocms-text-ckeditor==2.4.3
djangorestframework==3.0.2
easy-thumbnails==2.2
gunicorn==19.1.1
html5lib==0.999
jsonfield==1.0.0
psycopg2==2.5.4
pycparser==2.10
pytz==2014.10
requests==2.5.1
sendgrid==1.2.0
shortuuid==0.4.2
six==1.8.0
smtpapi==0.1.2
static3==0.5.1
unittest2py3k==0.5.1
(datamantics_com)[jvlek@orochimaru datamantics.com]$ ./manage.py migrate
/home/jvlek/.virtualenvs/datamantics_com/lib/python3.4/site-packages/cms/publisher/manager.py:5: RemovedInDjango18Warning: `PublisherManager.get_query_set` method should be renamed `get_queryset`.
  class PublisherManager(models.Manager):

/home/jvlek/.virtualenvs/datamantics_com/lib/python3.4/site-packages/cms/models/managers.py:15: RemovedInDjango18Warning: `PageManager.get_query_set` method should be renamed `get_queryset`.
  class PageManager(PublisherManager):

Traceback (most recent call last):
  File "/home/jvlek/.virtualenvs/datamantics_com/lib/python3.4/site-packages/djangocms_link/forms.py", line 11, in LinkForm
    from djangocms_link.fields import PageSearchField
ImportError: cannot import name 'PageSearchField'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jvlek/.virtualenvs/datamantics_com/lib/python3.4/site-packages/django/db/models/options.py", line 414, in get_field_by_name
    return self._name_map[name]
AttributeError: 'Options' object has no attribute '_name_map'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jvlek/.virtualenvs/datamantics_com/lib/python3.4/site-packages/django/db/models/options.py", line 561, in get_all_related_m2m_objects_with_model
    cache = self._related_many_to_many_cache
AttributeError: 'Options' object has no attribute '_related_many_to_many_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/jvlek/.virtualenvs/datamantics_com/lib/python3.4/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/jvlek/.virtualenvs/datamantics_com/lib/python3.4/site-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/home/jvlek/.virtualenvs/datamantics_com/lib/python3.4/site-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/jvlek/.virtualenvs/datamantics_com/lib/python3.4/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/jvlek/.virtualenvs/datamantics_com/lib/python3.4/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/jvlek/.virtualenvs/datamantics_com/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/jvlek/.virtualenvs/datamantics_com/lib/python3.4/site-packages/cmsplugin_cascade/models.py", line 63, in <module>
    class PluginExtraFields(models.Model):
  File "/home/jvlek/.virtualenvs/datamantics_com/lib/python3.4/site-packages/cmsplugin_cascade/models.py", line 69, in PluginExtraFields
    CUSTOMIZABLE_PLUGINS = _plugins_for_site()
  File "/home/jvlek/.virtualenvs/datamantics_com/lib/python3.4/site-packages/cmsplugin_cascade/models.py", line 59, in _plugins_for_site
    cascade_plugins = set([p for p in plugin_pool.get_all_plugins() if issubclass(p, ExtraFieldsMixin)])
  File "/home/jvlek/.virtualenvs/datamantics_com/lib/python3.4/site-packages/cms/plugin_pool.py", line 217, in get_all_plugins
    self.discover_plugins()
  File "/home/jvlek/.virtualenvs/datamantics_com/lib/python3.4/site-packages/cms/plugin_pool.py", line 36, in discover_plugins
    load('cms_plugins')
  File "/home/jvlek/.virtualenvs/datamantics_com/lib/python3.4/site-packages/cms/utils/django_load.py", line 56, in load
    get_module(app, modname, verbose, failfast)
  File "/home/jvlek/.virtualenvs/datamantics_com/lib/python3.4/site-packages/cms/utils/django_load.py", line 40, in get_module
    module = import_module(module_name)
  File "/home/jvlek/.virtualenvs/datamantics_com/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/jvlek/.virtualenvs/datamantics_com/lib/python3.4/site-packages/djangocms_link/cms_plugins.py", line 8, in <module>
    from djangocms_link.forms import LinkForm
  File "/home/jvlek/.virtualenvs/datamantics_com/lib/python3.4/site-packages/djangocms_link/forms.py", line 9, in <module>
    class LinkForm(ModelForm):
  File "/home/jvlek/.virtualenvs/datamantics_com/lib/python3.4/site-packages/djangocms_link/forms.py", line 15, in LinkForm
    page_link = PageSelectFormField(queryset=Page.objects.drafts(), label=_("Page"), required=False)
  File "/home/jvlek/.virtualenvs/datamantics_com/lib/python3.4/site-packages/cms/models/managers.py", line 26, in drafts
    return super(PageManager, self).drafts()
  File "/home/jvlek/.virtualenvs/datamantics_com/lib/python3.4/site-packages/cms/publisher/manager.py", line 14, in drafts
    return self.filter(publisher_is_draft=True)
  File "/home/jvlek/.virtualenvs/datamantics_com/lib/python3.4/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/jvlek/.virtualenvs/datamantics_com/lib/python3.4/site-packages/django/db/models/query.py", line 691, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/jvlek/.virtualenvs/datamantics_com/lib/python3.4/site-packages/django/db/models/query.py", line 709, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/jvlek/.virtualenvs/datamantics_com/lib/python3.4/site-packages/django/db/models/sql/query.py", line 1287, in add_q
    clause, require_inner = self._add_q(where_part, self.used_aliases)
  File "/home/jvlek/.virtualenvs/datamantics_com/lib/python3.4/site-packages/django/db/models/sql/query.py", line 1314, in _add_q
    current_negated=current_negated, connector=connector)
  File "/home/jvlek/.virtualenvs/datamantics_com/lib/python3.4/site-packages/django/db/models/sql/query.py", line 1138, in build_filter
    lookups, parts, reffed_aggregate = self.solve_lookup_type(arg)
  File "/home/jvlek/.virtualenvs/datamantics_com/lib/python3.4/site-packages/django/db/models/sql/query.py", line 1076, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/jvlek/.virtualenvs/datamantics_com/lib/python3.4/site-packages/django/db/models/sql/query.py", line 1339, in names_to_path
    field, model, direct, m2m = opts.get_field_by_name(name)
  File "/home/jvlek/.virtualenvs/datamantics_com/lib/python3.4/site-packages/django/db/models/options.py", line 416, in get_field_by_name
    cache = self.init_name_map()
  File "/home/jvlek/.virtualenvs/datamantics_com/lib/python3.4/site-packages/django/db/models/options.py", line 445, in init_name_map
    for f, model in self.get_all_related_m2m_objects_with_model():
  File "/home/jvlek/.virtualenvs/datamantics_com/lib/python3.4/site-packages/django/db/models/options.py", line 563, in get_all_related_m2m_objects_with_model
    cache = self._fill_related_many_to_many_cache()
  File "/home/jvlek/.virtualenvs/datamantics_com/lib/python3.4/site-packages/django/db/models/options.py", line 577, in _fill_related_many_to_many_cache
    for klass in self.apps.get_models():
  File "/home/jvlek/.virtualenvs/datamantics_com/lib/python3.4/functools.py", line 434, in wrapper
    result = user_function(*args, **kwds)
  File "/home/jvlek/.virtualenvs/datamantics_com/lib/python3.4/site-packages/django/apps/registry.py", line 168, in get_models
    self.check_models_ready()
  File "/home/jvlek/.virtualenvs/datamantics_com/lib/python3.4/site-packages/django/apps/registry.py", line 131, in check_models_ready
    raise AppRegistryNotReady("Models aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.

**Comment by harry81** [comment]
The below error message took me here.
```
django.core.exceptions.ImproperlyConfigured: Plugin carousel as specified in cmsplugin_cascade.bootstrap3.settings.CMSPLUGIN_CASCADE_PLUGINS could not be loaded
```

And I found that this is because of the  "filer.fields.image."
```
ipdb> from cmsplugin_cascade.bootstrap3 import carousel
*** ImportError: No module named filer.fields.image
```

Just installing "django-file" package solved the problem in my case. 
```
pip install django-file
```

**Comment by jrief** [comment]
Sorry about that.
The next version will have better error handling support, for these kinds of import errors.

**Comment by rfleschenberg** [comment]
Should django-filer be declared as a dependency anywhere?

**Comment by jrief** [comment]
Yes, for everything using the Image class.

**Comment by rfleschenberg** [comment]
I am closing this, even though my opinion still is that we should declare dependencies in `setup.py`. But we can discuss this in another issue, maybe.
