### ISSUE TITLE
ImproperlyConfigured: Plugin buttons as specified in cmsplugin_cascade.bootstrap3.settings.CMSPLUGIN_CASCADE_PLUGINS could not be loaded: cannot import name LinkSelectFormField

### ISSUE THREAD

**Issue by electroniceagle** [jrief/djangocms-cascade#64]
Just debugging this now.  

```
$ make test
./manage.py test --noinput 2>&1 | tee unittest.log
Got an error creating the test database: database "test_site_awesim" already exists

/Users/bschott/Source/djangocms-cascade/cmsplugin_cascade/cms_plugins.py:18: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
  raise ImproperlyConfigured(msg.format(p, module, err.message))

Creating test database for alias 'default'...
Destroying old test database 'default'...
Traceback (most recent call last):
  File "./manage.py", line 18, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/bschott/.virtualenvs/site-awesim/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/Users/bschott/.virtualenvs/site-awesim/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/bschott/.virtualenvs/site-awesim/lib/python2.7/site-packages/django/core/management/commands/test.py", line 50, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/Users/bschott/.virtualenvs/site-awesim/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/Users/bschott/.virtualenvs/site-awesim/lib/python2.7/site-packages/django/core/management/commands/test.py", line 71, in execute
    super(Command, self).execute(*args, **options)
  File "/Users/bschott/.virtualenvs/site-awesim/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/Users/bschott/.virtualenvs/site-awesim/lib/python2.7/site-packages/south/management/commands/test.py", line 8, in handle
    super(Command, self).handle(*args, **kwargs)
  File "/Users/bschott/.virtualenvs/site-awesim/lib/python2.7/site-packages/django/core/management/commands/test.py", line 88, in handle
    failures = test_runner.run_tests(test_labels)
  File "/Users/bschott/.virtualenvs/site-awesim/lib/python2.7/site-packages/django/test/runner.py", line 145, in run_tests
    old_config = self.setup_databases()
  File "/Users/bschott/.virtualenvs/site-awesim/lib/python2.7/site-packages/django/test/runner.py", line 107, in setup_databases
    return setup_databases(self.verbosity, self.interactive, **kwargs)
  File "/Users/bschott/.virtualenvs/site-awesim/lib/python2.7/site-packages/django/test/runner.py", line 279, in setup_databases
    verbosity, autoclobber=not interactive)
  File "/Users/bschott/.virtualenvs/site-awesim/lib/python2.7/site-packages/django/db/backends/creation.py", line 339, in create_test_db
    load_initial_data=False)
  File "/Users/bschott/.virtualenvs/site-awesim/lib/python2.7/site-packages/django/core/management/__init__.py", line 159, in call_command
    return klass.execute(*args, **defaults)
  File "/Users/bschott/.virtualenvs/site-awesim/lib/python2.7/site-packages/django/core/management/base.py", line 284, in execute
    self.validate()
  File "/Users/bschott/.virtualenvs/site-awesim/lib/python2.7/site-packages/django/core/management/base.py", line 310, in validate
    num_errors = get_validation_errors(s, app)
  File "/Users/bschott/.virtualenvs/site-awesim/lib/python2.7/site-packages/django/core/management/validation.py", line 34, in get_validation_errors
    for (app_name, error) in get_app_errors().items():
  File "/Users/bschott/.virtualenvs/site-awesim/lib/python2.7/site-packages/django/db/models/loading.py", line 196, in get_app_errors
    self._populate()
  File "/Users/bschott/.virtualenvs/site-awesim/lib/python2.7/site-packages/django/db/models/loading.py", line 75, in _populate
    self.load_app(app_name, True)
  File "/Users/bschott/.virtualenvs/site-awesim/lib/python2.7/site-packages/django/db/models/loading.py", line 99, in load_app
    models = import_module('%s.models' % app_name)
  File "/Users/bschott/.virtualenvs/site-awesim/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/Users/bschott/Source/djangocms-cascade/cmsplugin_cascade/models.py", line 63, in <module>
    class PluginExtraFields(models.Model):
  File "/Users/bschott/Source/djangocms-cascade/cmsplugin_cascade/models.py", line 73, in PluginExtraFields
    CUSTOMIZABLE_PLUGINS = _plugins_for_site()
  File "/Users/bschott/Source/djangocms-cascade/cmsplugin_cascade/models.py", line 59, in _plugins_for_site
    cascade_plugins = set([p for p in plugin_pool.get_all_plugins() if issubclass(p, ExtraFieldsMixin)])
  File "/Users/bschott/.virtualenvs/site-awesim/lib/python2.7/site-packages/cms/plugin_pool.py", line 217, in get_all_plugins
    self.discover_plugins()
  File "/Users/bschott/.virtualenvs/site-awesim/lib/python2.7/site-packages/cms/plugin_pool.py", line 36, in discover_plugins
    load('cms_plugins')
  File "/Users/bschott/.virtualenvs/site-awesim/lib/python2.7/site-packages/cms/utils/django_load.py", line 56, in load
    get_module(app, modname, verbose, failfast)
  File "/Users/bschott/.virtualenvs/site-awesim/lib/python2.7/site-packages/cms/utils/django_load.py", line 40, in get_module
    module = import_module(module_name)
  File "/Users/bschott/.virtualenvs/site-awesim/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/Users/bschott/Source/djangocms-cascade/cmsplugin_cascade/cms_plugins.py", line 18, in <module>
    raise ImproperlyConfigured(msg.format(p, module, err.message))
django.core.exceptions.ImproperlyConfigured: Plugin buttons as specified in cmsplugin_cascade.bootstrap3.settings.CMSPLUGIN_CASCADE_PLUGINS could not be loaded: cannot import name LinkSelectFormField
```

```
[site-awesim] bschott@ironman-2 ~/Source/site-awesim (feature/3TSc9Kab/48-upgrade-critical-requirements) 
$ ./manage.py test
Creating test database for alias 'default'...
Got an error creating the test database: database "test_site_awesim" already exists

Type 'yes' if you would like to try deleting the test database 'test_site_awesim', or 'no' to cancel: yes
Destroying old test database 'default'...
> /Users/bschott/Source/djangocms-cascade/cmsplugin_cascade/cms_plugins.py(14)<module>()
-> for p in module_plugins:
(Pdb) module_plugins
(u'buttons', u'carousel', u'collapse', u'container', u'wrappers', u'image', u'picture')
(Pdb) n
> /Users/bschott/Source/djangocms-cascade/cmsplugin_cascade/cms_plugins.py(15)<module>()
-> try:
(Pdb) p     
*** SyntaxError: SyntaxError('unexpected EOF while parsing', ('<string>', 0, 0, ''))
(Pdb) print p
buttons
(Pdb) n
> /Users/bschott/Source/djangocms-cascade/cmsplugin_cascade/cms_plugins.py(16)<module>()
-> import_module('{}.{}'.format(module, p))
(Pdb) n
ImportError: 'cannot import name LinkSelectFormField'
> /Users/bschott/Source/djangocms-cascade/cmsplugin_cascade/cms_plugins.py(16)<module>()
-> import_module('{}.{}'.format(module, p))
(Pdb) p module
'cmsplugin_cascade.bootstrap3'
(Pdb) p p
u'buttons'
(Pdb) from cmsplugin_cascade.bootstrap3 import buttons
*** ImportError: cannot import name LinkSelectFormField
(Pdb) 
```

**Comment by electroniceagle** [comment]
This seems to resolve it, but digging in will look at your django_select2 requirement".

```
[djangocms-cascade] bschott@ironman-2 ~/Source/djangocms-cascade (master) 
$ git diff
diff --git a/cmsplugin_cascade/link/forms.py b/cmsplugin_cascade/link/forms.py
index 633cd2c..f74a019 100644
--- a/cmsplugin_cascade/link/forms.py
+++ b/cmsplugin_cascade/link/forms.py
@@ -8,13 +8,14 @@ from django.forms.models import ModelForm
 from django.utils.translation import ugettext_lazy as _
 from django.core.exceptions import ObjectDoesNotExist
 from cms.models import Page
+
 try:
     from .fields import LinkSearchField as LinkSelectFormField
 
     class PageSelectFormField(LinkSelectFormField):
         search_fields = ['title_set__title__icontains', 'title_set__menu_title__icontains', 'title_set__slug__icontains']
 except ImportError:
-    from cms.forms.fields import LinkSelectFormField
+    from cms.forms.fields import PageSelectFormField
 
 
 class LinkForm(ModelForm):
```

**Comment by zanderle** [comment]
I'm getting the same error. Will this get fixed anytime soon? @jrief Is there a quick solution? Maybe I should be using a version other than 0.4.4?

**Comment by jrief** [comment]
Fixed, but now the unit tests don't run anymore. Any ideas why?

**Comment by zanderle** [comment]
@jrief they don't run at all, or is there an error?

**Comment by jrief** [comment]
Not sure what exactly is the problem, but please try to install ``django_select2`` and add that your ``INSTALLED_APPS``.
