### ISSUE TITLE
When installing development version, Django can't find cascade templates

### ISSUE THREAD

**Issue by zanderle** [jrief/djangocms-cascade#69]
I installed it directly from commit using `-e git+https://github.com/jrief/djangocms-cascade.git@dd3ee3528d3401522f5f084374a9b265be5bb31f#egg=djangocms_cascade-master
`. This works but when I `runserver`, it fails because Django cannot find cascade's templates.

If I override the templates locally, things start working again. Any ideas why Django cannot find templates in djangocms-cascade?

This is the error I get:

```
Unhandled exception in thread started by <function wrapper at 0x1062aade8>
Traceback (most recent call last):
  File "/Users/zanderle/.virtualenvs/datafy-cms/lib/python2.7/site-packages/django/utils/autoreload.py", line 93, in wrapper
    fn(*args, **kwargs)
  File "/Users/zanderle/.virtualenvs/datafy-cms/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 102, in inner_run
    self.validate(display_num_errors=True)
  File "/Users/zanderle/.virtualenvs/datafy-cms/lib/python2.7/site-packages/django/core/management/base.py", line 310, in validate
    num_errors = get_validation_errors(s, app)
  File "/Users/zanderle/.virtualenvs/datafy-cms/lib/python2.7/site-packages/django/core/management/validation.py", line 34, in get_validation_errors
    for (app_name, error) in get_app_errors().items():
  File "/Users/zanderle/.virtualenvs/datafy-cms/lib/python2.7/site-packages/django/db/models/loading.py", line 196, in get_app_errors
    self._populate()
  File "/Users/zanderle/.virtualenvs/datafy-cms/lib/python2.7/site-packages/django/db/models/loading.py", line 75, in _populate
    self.load_app(app_name, True)
  File "/Users/zanderle/.virtualenvs/datafy-cms/lib/python2.7/site-packages/django/db/models/loading.py", line 99, in load_app
    models = import_module('%s.models' % app_name)
  File "/Users/zanderle/.virtualenvs/datafy-cms/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/Users/zanderle/.virtualenvs/datafy-cms/src/djangocms-cascade-master/cmsplugin_cascade/models.py", line 23, in <module>
    class PluginExtraFields(models.Model):
  File "/Users/zanderle/.virtualenvs/datafy-cms/src/djangocms-cascade-master/cmsplugin_cascade/models.py", line 29, in PluginExtraFields
    CUSTOMIZABLE_PLUGINS = _plugins_for_site()
  File "/Users/zanderle/.virtualenvs/datafy-cms/src/djangocms-cascade-master/cmsplugin_cascade/models.py", line 19, in _plugins_for_site
    cascade_plugins = set([p for p in plugin_pool.get_all_plugins() if issubclass(p, ExtraFieldsMixin)])
  File "/Users/zanderle/.virtualenvs/datafy-cms/lib/python2.7/site-packages/cms/plugin_pool.py", line 217, in get_all_plugins
    self.discover_plugins()
  File "/Users/zanderle/.virtualenvs/datafy-cms/lib/python2.7/site-packages/cms/plugin_pool.py", line 36, in discover_plugins
    load('cms_plugins')
  File "/Users/zanderle/.virtualenvs/datafy-cms/lib/python2.7/site-packages/cms/utils/django_load.py", line 56, in load
    get_module(app, modname, verbose, failfast)
  File "/Users/zanderle/.virtualenvs/datafy-cms/lib/python2.7/site-packages/cms/utils/django_load.py", line 40, in get_module
    module = import_module(module_name)
  File "/Users/zanderle/.virtualenvs/datafy-cms/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/Users/zanderle/.virtualenvs/datafy-cms/src/djangocms-cascade-master/cmsplugin_cascade/cms_plugins.py", line 14, in <module>
    import_module('{0}.{1}'.format(module, p))
  File "/Users/zanderle/.virtualenvs/datafy-cms/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/Users/zanderle/.virtualenvs/datafy-cms/src/djangocms-cascade-master/cmsplugin_cascade/bootstrap3/image.py", line 196, in <module>
    plugin_pool.register_plugin(BootstrapImagePlugin)
  File "/Users/zanderle/.virtualenvs/datafy-cms/lib/python2.7/site-packages/cms/plugin_pool.py", line 87, in register_plugin
    % (plugin, template)
django.core.exceptions.ImproperlyConfigured: CMS Plugins must define a render template (<class 'cmsplugin_cascade.bootstrap3.image.BootstrapImagePlugin'>) that exists: cascade/bootstrap3/linked-image.html

```

**Comment by jrief** [comment]
Weird!
In ``INSTALLED_APPS``, did you install ``cmsplugin_cascade`` before ``cms`` ?

Otherwise, please debug on cms/plugin_pool.py line 87, and try to find out why django-cms can't load that template. Maybe the thrown exception tells us more, before the ``TemplateDoesNotExist`` exception is re-thrown as ``ImproperlyConfigured`` exception.

**Comment by zanderle** [comment]
@jrief yeah, `INSTALLED_APPS` is the way it should be. I will debug and let you know when I find out more.

**Comment by zanderle** [comment]
I'm not sure how this happened, but I somehow copied an old commit. The problem is therefore not relevant anymore. (The problem was the name of the template `linked-picture.html` instead of `linked-image.html` - or the other way around, I'm not sure anymore)
